MESSAGE(STATUS "Looking for pthread")

FIND_PATH(pthread_INCLUDE_DIR pthread.h)
SET(pthread_NAMES ${pthread_NAMES} pthread)
FIND_LIBRARY(pthread_LIBRARY NAMES ${pthread_NAMES} HPATHS /usr/lib/x86_64-linux-gnu)

IF (pthread_LIBRARY AND pthread_INCLUDE_DIR)
    SET(pthread_LIBRARIES ${pthread_LIBRARY})
    SET(pthread_INCLUDES ${pthread_INCLUDE_DIR})
    SET(pthread_FOUND "YES")
ELSE (pthread_LIBRARY AND pthread_INCLUDE_DIR)
    SET(pthread_FOUND "NO")
ENDIF (pthread_LIBRARY AND pthread_INCLUDE_DIR)

IF (pthread_FOUND)
    IF (NOT pthread_FIND_QUIETLY)
        MESSAGE(STATUS "Found pthread headers: ${pthread_INCLUDE_DIR}")
        MESSAGE(STATUS "Found pthread library: ${pthread_LIBRARIES}")
    ENDIF (NOT pthread_FIND_QUIETLY)
ELSE (pthread_FOUND)
    IF (pthread_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find pthread library")
    ENDIF (pthread_FIND_REQUIRED)
ENDIF (pthread_FOUND)